### ISSUE TITLE
Handling Multiple Sequencing Lanes and Donor Information in VireoSNP

### ISSUE THREAD

**Issue by sxf-ux** [single-cell-genetics/vireo#101]
Hello,

I am currently working with 10X single-cell RNA-seq data from multiple sequencing lanes and fragments. Specifically, I have a sample (Sample X) which has been sequenced in two lanes, resulting in BAM files for Sample X-1 and Sample X-2. Additionally, I have a sample (Sample Y) were Sample Y-1 and Sample Y-2 may come from different brain areas of the same individual.

I have processed these BAM files (they've been treated separately) using cellSNP-lite and MQuad where I have generated AD and DP matrices for each lane/fragment and relevant vcf files. Now, I am aiming to run VireoSNP for demultiplexing and clonal assignment.

My questions are as follows:

- Are there any best practices for using VireoSNP with data from multiple sequencing lanes or fragments to ensure accurate demultiplexing and clonal assignment? 

I understand that I need to specify donors before identifying clones so I need to understand what approach works best for my dataset. 

- How should I approach combining the AD and DP matrices from different lanes or fragments before running VireoSNP? Is there a recommended method or script to ensure correct merging? I also have VCF files for each sample (samples that have been run in different lanes or samples which have had multiple fragments)

Thank you in advance.

**Comment by huangyh09** [comment]
Thanks for your questions.

1) for different lanes, I assume that the same cell barcodes in two lanes refer to the cell cell, so I would suggest you run cellranger by inputting them together, so you will have a single bam file.
2) for two biological samples of a donor, one way to merge AD and DP is to keep the same list of variants (before or after cellsnp-lite) and then concatenate the cells. Another way is you use cellranger to merge two bams into a new bigger bam with cell barcodes with suffixes `-1` and `-2` for the two samples.

Yuanhua

**Comment by sxf-ux** [comment]
Thank you for the answer Yuanhua.

I had another question. how would i concatenate the cells? I am a little confused on how to approach this.

these are the cellsnp output files I have:

```
cellSNP.base.vcf.gz   cellSNP.samples.tsv  cellSNP.tag.DP.mtx
cellSNP.cells.vcf.gz  cellSNP.tag.AD.mtx   cellSNP.tag.OTH.mtx
```
