### ISSUE TITLE
_GT_donors.vireo.vcf.gz

### ISSUE THREAD

**Issue by hsymoon** [single-cell-genetics/vireo#111]
Hello developer,
    Thanks for your useful tool. Mode1_noGenotype,   Mode3_noConfidentGenotype_GTforce,  Mode4_partGenotype will produce a file like "*_GT_donors.vireo.vcf.gz",which describes the genotype of donors_vireo_identify.
    I wonder how it generate.Could you provide the function name or a link for it.Thanks!

**Comment by hsymoon** [comment]
I already found related functions like GeneInfo_marker, vireo_wrap , vireo .i.e. Sorry for that it seems difficult to me. Could developers provide the function ,which  could infer donor genotypes from  identified_results(like cell1 is identified from donor1, cell2 is identified from donor2).  or there are some tools could do this?  Thanks for help!

**Comment by huangyh09** [comment]
Hi, there is no separate function for this. It is embedded into the main class via its [update_GT_prob()](https://github.com/single-cell-genetics/vireo/blob/master/vireoSNP/utils/vireo_model.py#L204) subfunction.

If you need, you can use cellsnp-lite to perform genotyping again for the cells you identified.

Yuanhua
