### ISSUE TITLE
using Vireo for celseq2 data

### ISSUE THREAD

**Issue by dwkarjosukarso** [single-cell-genetics/vireo#12]
Hi, 
how feasible do you see the use of Vireo on celseq2 data?
With such plate based scRNA-seq, each plate has same combination of cell barcodes and it is not possible to control how much of donor 1 is sorted in to plate 1, etc.
Thanks,
Dyah

**Comment by huangyh09** [comment]
I'm not quite get your question, probably because I'm not very familiar with celseq2. May be you could explain the settings in more details, e.g., you have multiple donors in each plate, and you want to link donors or estimate donor proportions? Basically, Vireo clusters cells into donors by its (given or inferred) genotypes.

Yuanhua

**Comment by dwkarjosukarso** [comment]
Typically for celseq2, a few plates were sequenced from 1 sample to get enough cells sequenced. When we pool multiple donors into 1 sample and sort them into plates, we cannot control the equal distribution of the donors in the plates. However, the library for each plate is prepared separately and therefore has its own fastq and afterwards bam. I am wondering if it is feasible to use Vireo for such data then.

Dyah

**Comment by huangyh09** [comment]
Thanks Dyah. Yes, I think it should be feasible to use vireo on this. You could use [cellSNP](https://pypi.org/project/cellSNP/) mode 3 to genotype the cells in a sample (treating each cell as a bulk sample). This step requires known heterzygous SNPs from these donors or a list of common SNPs, e.g., from 1000 Genome as listed in cellSNP. Then, you run vireo on the output data to map these cells to donors or cluster them into donors.

Yuanhua
