### ISSUE TITLE
Vireo with both known and unknown genotypes in sample

### ISSUE THREAD

**Issue by bio-la** [single-cell-genetics/vireo#13]
Hi,
I think someone has already asked this but I can't find it now.
Would video work if I have a pool of 10 samples whose genotype is known and  +1/2 whose genotype is unknown?
i.e. would video accept a donor number param greater than what provided in the Variant calling, or is there anything I need to specify to cellsnp for the pileup too?

thank you!

**Comment by huangyh09** [comment]
Hi,
Yes, Vireo can handle this. As mentioned in the [manual](https://vireosnp.readthedocs.io/en/latest/manual.html), you can use the mode 3 with `-N $n_donor`  for your exact number in the pool and `-d $DONOR_GT_FILE` for the donors with known genotypes. Filter variant donor vcf with `bcftools` as mode 2 would save memories. Alternatively, you can run vireo without any donor genotype first and align them back to known genotype, like the [example here](https://github.com/single-cell-genetics/vireo/blob/master/examples/donor_match.ipynb).

For genotyping with cellsnp, you don't need to specify anything as the donor information is not used in this step.

Yuanhua

**Comment by bio-la** [comment]
Thank you!
