### ISSUE TITLE
Recommended tools for bulk RNA-seq genotyping for mode 2

### ISSUE THREAD

**Issue by lmweber** [single-cell-genetics/vireo#14]
Hi, do you have any recommendations for tools to use for genotyping multiple bulk RNA-seq samples for running in mode 2?

In our dataset, we have several matched bulk and single-cell RNA-seq samples. So far we have been using only the single-cell samples together with the VCF from 1000 Genomes Project, but we would also like to check if we can get improved performance by genotyping the matched bulk samples.

I am fairly new to this, so just want to check if there are any tools you do / do not recommend for the bulk genotyping. Thanks

**Comment by huangyh09** [comment]
Hi, it should be a better idea to genotyping the matched bulk samples. You can use bcftools, freebayes or cellSNP mode2, or others.

This benchmarking for single cells can be a useful reference: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1863-4
It treats each cell as a sample, so probably also fits well with bulk RNA-seq.

Yuanhua

**Comment by lmweber** [comment]
Ok great, thanks! I'll start by trying cellSNP mode 2 (since I am familiar with cellSNP now) or bcftools.

Thanks also for the reference.
