### ISSUE TITLE
Recovering donor identity in known genotype mode

### ISSUE THREAD

**Issue by vals** [single-cell-genetics/vireo#17]
Hi,

When running vireo (for known genotypes) the output per cell is noted as `donor0` to `donorN`. Is there a way to go from these labels to the genotype names in the reference VCF file input to cellsnp-lite?

**Comment by huangyh09** [comment]
Hi,

Thanks for reporting this. It is indeed a bug when changing the shape of the genotype probability tensor. It should be fixed by this [commit](https://github.com/single-cell-genetics/vireo/commit/96a295544438f79c55ab4f48eb8b383581b2f791). Let us know if it does in your data.

Yuanhua

**Comment by vals** [comment]
Hi Yuanhua,

Thanks! I also learned by trying things that you get the donors when not providing the `-N` option. But this will allow me to use this feature.

Is the fixed version released on PYPI or does it need to be installed from the github?

/Valentine

**Comment by huangyh09** [comment]
Hi Valentine, indeed if not providing `-N` should work, it should have worked, while this requires your donor_VCF has the same number of donors. 

Yes, you can get the fixed version on PYPI, which is the same as the latest in github.

Yuanhua
