### ISSUE TITLE
option cell_file not defined

### ISSUE THREAD

**Issue by Zepeng-Mu** [single-cell-genetics/vireo#26]
Hi, I got this error:
```
Traceback (most recent call last):
  File "/home/[user]/miniconda3/bin/vireo", line 8, in <module>
    sys.exit(main())
  File "/home/[user]/miniconda3/lib/python3.8/site-packages/vireoSNP/vireo.py", line 98, in main
    out_dir = os.path.dirname(os.path.abspath(options.cell_file)) + "/vireo"
AttributeError: 'Values' object has no attribute 'cell_file'
```
https://github.com/single-cell-genetics/vireo/blob/bdebfdfc5b2326172f46a2808eb762ced2bbe802/vireoSNP/vireo.py#L98
Should this be `cell_data`?

Thanks!

**Comment by huangyh09** [comment]
Thanks for reporting it. I just fixed:
https://github.com/single-cell-genetics/vireo/commit/12df6fc17dad1bd1825bdf7b597fc3e062452130#diff-4e9960e1ab86072ca8babcaa4836e3bd16f7bd1789bb61a34ce2799a1f1217ec

Yuanhua
