### ISSUE TITLE
cellSNP-lite incompatibility

### ISSUE THREAD

**Issue by drneavin** [single-cell-genetics/vireo#31]
Hello,

I recently switched to using cellSNP-lite for vireo SNP preprocessing but ran into an issue when using those results for Vireo. It seems that Vireo anticipates the cellSNP-lite results to output `cellSNP.base.vcf.gz` but instead it outputs `cellSNP.base.vcf`.

The error message I receive is:
```
FileNotFoundError: [Errno 2] No such file or directory: 'cellSNP.base.vcf.gz'
```

The files in the directory after running cellsnp-lite are:
```
	.
	├── cellSNP.base.vcf
	├── cellSNP.samples.tsv
	├── cellSNP.tag.AD.mtx
	├── cellSNP.tag.DP.mtx
	└── cellSNP.tag.OTH.mtx
```

I am using cellSNP-lite v1.2.1 installed with conda and vireoSNP v0.5.6 installed with pip.

Thanks for your help!

**Comment by hxj5** [comment]
Maybe add `--gzip` option for cellsnp-lite would make it output `cellSNP.base.vcf.gz` instead of `cellSNP.base.vcf`.

**Comment by drneavin** [comment]
Yes, you are right @hxj5! The `--gzip` option does exactly what I was looking for.
