### ISSUE TITLE
Demultiplexing pooled samples w/o genotype (dialing number of samples)

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [single-cell-genetics/vireo#35]
Hi,

I tested vireo for 4 samples (we do not have genotype data).
`vireo -c $CELL_DIR -N 4 -o $OUT_DIR --randSeed 2`

The distribution of cells, doublet and unassigned cells look great
```
Var1    Freq
donor0  1344
donor1  1732
donor2  1384
donor3  1844
doublet 227
unassigned      3
```
We ran the same pipeline but instead of 4 samples to experiment we input 3 "as number of samples". we were hoping by doing this the cell count for 4th sample would be unassigned, however the results now look a bit concerning
```
Var1    Freq
donor0  1735
donor1  1843
donor2  2606
doublet 290
unassigned      60
```
 Let us know whet you think.

Thank you!
Parul

**Comment by huangyh09** [comment]
Hi Parul,

Thanks for exploring the robustness of the model. The 3-sample "misspecification" indeed gave concerning results, while it seems still partly reasonable (I guess): donor0 & donor 2 --> donor2; donor1 --> donor 0; donor3 --> donor1. 

The model falsely conders that original donor0 and donor2 are one donor, probably because these two donors are relatively similar among the four.

Actually, this type of outcome is common in clustering, as it is generally difficult to define unassigned. One way for diagnosis is to check the similarity of the genotypes between the identified donors, which is provided in the "fig_GT_distance_estimated.pdf" file.

Yuanhua

**Comment by Parul-Kudtarkar** [comment]
Thank you so much @huangyh09 for a very prompt solution! 
The genotype distance between samples for N =4 (the actual number of pooled samples in scRNA-seq assay).  For two samples to be similar you would expect the probability close to 0, which is not the case here. So the genotype assignment for 3 sample "mis-specification" still remains concerning

<img width="705" alt="Screen Shot 2021-12-18 at 9 35 04 PM" src="https://user-images.githubusercontent.com/22722805/146665206-24762857-8789-4ad9-bdd6-024a7df262bf.png">

On that note, we obtained gentotypes for these samples so that we can run vireo in mode 2(with genotype)

We first run cellranger count/in case of scATAC we run `cellranger-atac count`
`nohup cellranger count --id=run_count_samples_12k_2 --transcriptome=/home/ubuntu/refdata-gex-GRCh38-2020-A --sample=samples_12K_2 --fastqs=/home/ubuntu/rnasamples`

We than run cellSNP with the genotype vcf file for our sample rather than using the 1000 genome reference vcf files. However, cellSNP run forever 
For scRNA-seq

`cellSNP -b /home/ubuntu/scrna/outs/filtered_tf_bc_matrix/barcodes.tsv -s /home/ubuntu/scrna/outs/possorted_bam.bam -O out -R my-samples.vcf -p 22 --minMAF 0.1 --minCOUNT 100`

For scATAC-seq we run with option UMItag=None
 `cellSNP -b /home/ubuntu/tgn/outs/filtered_tf_bc_matrix/barcodes.tsv -s /home/ubuntu/tgn/outs/possorted_bam.bam -O tgn-out -R my-samples.vcf -p 22 --minMAF 0.1 --minCOUNT 100 --UMItag None`

PS. cellSNP takes few hours when we provide the 1000 genome vcf reference. 
Let me know what you think.

Thank you!
Parul

**Comment by Parul-Kudtarkar** [comment]
Hi @huangyh09,

An update - we got genotypes for our samples. Vireo results for distribution of cells, doublet and unassigned cells without genotype (mode1) and with genotype (mode2) match!!

Thank you,
Parul
