### ISSUE TITLE
GitHub shows 0.2.3 as latest release

### ISSUE THREAD

**Issue by paulmenzel** [single-cell-genetics/vireo#60]
The current release seems to be 0.5.5, but GitHub shows 0.2.3 on the [releases page](https://github.com/single-cell-genetics/vireo/releases/) (and therefore the project page).

Maybe it’d be enough to tag the corresponding commits with `git tag <commit hash>`?

**Comment by huangyh09** [comment]
Thanks. We don't generate releases on GitHub anymore, as you can directly use the commit hash. Instead, we release it on PyPI: https://pypi.org/project/vireoSNP/

Yuanhua

**Comment by paulmenzel** [comment]
Understood, it’s still confusing though, and git tags or still a useful feature, so I’d recommend to add those. It shouldn’t impact PyPi, and tags just allow easy download of the source code in question, and users do not expect a release.
