### ISSUE TITLE
Multiome data demultiplexing

### ISSUE THREAD

**Issue by zhijunyuu** [single-cell-genetics/vireo#63]
Hey,

Thanks for the nice tool.

I have some 10x Multiome data, two donors were pooled for one reaction. In this case, I use cellSNP-lite and vireo to demultiplex scRNA and scATAC data independently. Most of the cells are assigned consistently within these two datasets, but some of them are not. Is there any way to to the demultiplex together via combining scRNA and scATAC data regarding they come from the same cell? Thanks in advance!

Here is the eg:
1) result from scATAC data:
`Var1	Freq
donor0	1877
donor1	2416
doublet	370
unassigned	902`

2) result from scRNA data:
`Var1	Freq
donor0	1844
donor1	2707
doublet	322
unassigned	692`

Best,
Zhijun

**Comment by huangyh09** [comment]
Thanks for sharing. It's a good point to combine the two modules, particularly for reducing the unassigned cells.

However, Vireo doesn't have a function to do so. Here are two potential options:
1. Append the SNPs between the two omics, and ignore that they may come from the same SNP. It may have the computational convenience to simply append the sparse matrices between to modules.
2. Sum the matrices between the two omics, if you keep the same set of SNPs. One limitation could be that UMI is used in scRNA but not in scATAC module.

Yuanhua

**Comment by zhijunyuu** [comment]
Hi Yuanhua,

Thanks for the reply. 
I tried append the matrix (output from cellsnp-list) from the two omics and run vireo. It works!
Here is the result, I think it is already much better than single dataset regarding the reduced number of unassigned cells:

`Var1	Freq
donor0	2929
donor1	2181
doublet	416
unassigned	39`

Best,
Zhijun

**Comment by DHelix** [comment]
> Hi Yuanhua,
> 
> Thanks for the reply. I tried append the matrix (output from cellsnp-lite) from the two omics and run vireo. It works! Here is the result, I think it is already much better than single dataset regarding the reduced number of unassigned cells:
> 
> `Var1 Freq donor0 2929 donor1 2181 doublet 416 unassigned 39`
> 
> Best, Zhijun

Hi @zhijunyuu,
I've been working on merging scRNA and scATAC data from scMultiome data for demultiplexing. Could you please explain how you appended the cellsnp-lite output matrices?
Thanks a lot!
