### ISSUE TITLE
-N flag behavior

### ISSUE THREAD

**Issue by racng** [single-cell-genetics/vireo#68]
If I know that a sample has only 10 donors and my donor genotype file has exactly 10 samples. Would adding`-N 10` flag change the behavior of vireo? Would it try to do some kind of learning and clustering first if I provide `-N`? Or try to directly match with the genotype file?

**Comment by huangyh09** [comment]
Hi, if they are equal, `-N` will be omitted. When `-N` is larger than that in donor VCF, then it will do clustering first then match to that in VCF.

Yuanhua
