### ISSUE TITLE
Output genotype data with vartrix files

### ISSUE THREAD

**Issue by GWW** [single-cell-genetics/vireo#7]
Is it possible to output the inferred genotypes when using vartrix data as input? I noticed in the code that when vartrix files are specified the genotypes will not be written.

```
    # ## save inferred donor genotype
    if learn_GT and options.vartrix_data is None:
```

**Comment by huangyh09** [comment]
Hi, atm, vireo doesn't support outputing the estimated donor genotype. The main reason is that there is no variant information, e.g., in VCF format, in the input, when we introduce this feature.

Before we introduce this feature, there could be two solutions:
1) modify the vireo.py [codes](https://github.com/single-cell-genetics/vireo/blob/master/vireoSNP/vireo.py#L226) and save the genotype probability even without the variants information, as they are in the same order as input.
2) change the vartrix matrix files into cellSNP format by adding variants VCF. Alternatively, you could run cellSNP on your data.

Yuanhua

**Comment by GWW** [comment]
Thanks for the reply.  I don't mind modifying the code to use your first solution if you could point me in the right variables to get the p-value data.

**Comment by huangyh09** [comment]
Sure, you could basically change these [codes](https://github.com/single-cell-genetics/vireo/blob/master/vireoSNP/vireo.py#L226):
```
    ## save inferred donor genotype
    if learn_GT and options.vartrix_data is None:
        donor_vcf_out = cell_vcf
        donor_vcf_out['samples'] = donor_names
        donor_vcf_out['GenoINFO'] = GenoINFO_maker(res_vireo['GT_prob'], 
            cell_dat['AD'] * res_vireo['ID_prob'], 
            cell_dat['DP'] * res_vireo['ID_prob'])
        write_VCF(out_dir + "/GT_donors.vireo.vcf.gz", donor_vcf_out)
```

to 

```
    ## save inferred donor genotype
    if learn_GT and options.vartrix_data is None:
        donor_vcf_out = cell_vcf
        donor_vcf_out['samples'] = donor_names
        donor_vcf_out['GenoINFO'] = GenoINFO_maker(res_vireo['GT_prob'], 
            cell_dat['AD'] * res_vireo['ID_prob'], 
            cell_dat['DP'] * res_vireo['ID_prob'])
        write_VCF(out_dir + "/GT_donors.vireo.vcf.gz", donor_vcf_out)
    elif options.vartrix_data is not None:
        np.savez(out_dir + "/GT_donors.vireo.npz", res_vireo['ID_prob'], cell_dat['AD'], cell_dat['DP'])
```
 
see numpy.savez from [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html)

**Comment by GWW** [comment]
Great thanks a lot!
