### ISSUE TITLE
Using Simulate to make distinct barcodes

### ISSUE THREAD

**Issue by Sun-storm** [single-cell-genetics/vireo#91]
Hi!

This is not an issue, but a question, and I didn't know where to ask it.

I have some scATAC-seq data in four BAM files. I wish to merge and then demultiplex them, but from what I have read I will have to modify the barcodes to make them distinct. I see you have developed a tool to do this, Simulate, and I wanted to ask if I have properly understood what I have to do.

Should I install Simulate and use the command `--barcodeFiles` with my 4 BAMs to modify their barcode and then merge them? Is this correct, or am I making some mistake?

Thank you very much for your kind answers.

Jan

**Comment by huangyh09** [comment]
it looks like you are doing some simulation experiments. Yes, our Simulate probably can support scATAC-seq too. You can follow the manual.

Yuanhua

**Comment by Sun-storm** [comment]
Excuse me for the late answer. Unless I am misunderstanding what a simulation experiment is, I am afraid that's not what I am doing. I have some patient data on which I'm performing an analysis. I need to demultiplex the data, but as it is in 4 different files and the barcodes overlap, I need to change them to merge them. This being the case, do you still consider it possible to use Simulate on my data?

Thank you for your answer!

**Comment by huangyh09** [comment]
Oh, in this case, you don't need the simulation. The simulator was designed to evaluate the model.

I still don't know why you have the same (or overlapped) pool in different files, you may not necessarily need to merge them. You can demultiplex them separately and link the donors later. Just in case if they are all from the same pool (but different lanes), you can put them together before giving to cellranger.

Yuanhua
