### ISSUE TITLE
Low doublet detection rate

### ISSUE THREAD

**Issue by DHelix** [single-cell-genetics/vireo#98]
Hi!
I've been experimenting with vireo using synthetic pools, created either with the synth_pool.py script or my own script. I noticed that vireo is missing around 50% of the doublets, which could be a concern, especially if the doublet rate is high due to overloading. Do you have any tips to enhance the detection rate?
Thanks!

**Comment by huangyh09** [comment]
Hi, this partly depends on the number of samples in the pool. For smaller numbers, the cross-donor doublets will lower, hence missing more doublts. In general, the detection of doublets is less optimal, especially if not provide the genotypes.

Yuanhua
